export const TRACKS = [
  {
    id: "coast",
    name: "Azure Coast",
    region: "PORT AZURE · RIVIERA",
    subtitle: "Salt air. Late brakes.",
    difficulty: 2,
    theme: "coast",
    width: 14,
    elevation: 2.0,
    points: [
      [0, 0],
      [0, -95],
      [45, -150],
      [135, -155],
      [195, -108],
      [170, -40],
      [217, 30],
      [180, 104],
      [91, 116],
      [38, 80],
      [-50, 85],
      [-83, 26],
      [-53, -13],
    ],
    color: "#69b8c0",
    description:
      "A fast waterfront circuit, sweeping harbor turns, and a technical run through the palms.",
  },
  {
    id: "canyon",
    name: "Ember Canyon",
    region: "RED ROCK · BADLANDS",
    subtitle: "Make your own thunder.",
    difficulty: 3,
    theme: "canyon",
    width: 13,
    elevation: 6.5,
    points: [
      [0, 0],
      [0, -80],
      [55, -126],
      [124, -109],
      [146, -42],
      [94, -7],
      [150, 55],
      [102, 132],
      [28, 103],
      [-30, 148],
      [-89, 94],
      [-95, 10],
      [-45, -25],
    ],
    color: "#d59b68",
    description:
      "Climb through red-rock country. Blind crests and tight switchbacks reward a clean line.",
  },
  {
    id: "night",
    name: "Afterlight",
    region: "NOVA CITY · MIDNIGHT",
    subtitle: "Own the after hours.",
    difficulty: 4,
    theme: "night",
    width: 14,
    elevation: 1.2,
    points: [
      [0, 0],
      [0, -108],
      [56, -149],
      [118, -120],
      [130, -60],
      [205, -56],
      [227, 3],
      [193, 78],
      [134, 57],
      [109, 128],
      [35, 141],
      [-48, 82],
      [-51, 13],
    ],
    color: "#859abe",
    description:
      "A midnight street circuit with long straights, lit towers, and unforgiving hairpins.",
  },
];
export const VEHICLES = [
  {
    id: "vortex",
    name: "Vortex RS",
    tag: "THE ALL-ROUNDER",
    drive: "RWD",
    mass: 168,
    power: 17.5,
    maxSpeed: 43,
    grip: 8.8,
    brake: 25,
    color: "#f26535",
    body: 0,
    text: "Light on its feet. Heavy on character.",
  },
  {
    id: "vector",
    name: "Vector GT",
    tag: "THE CORNER CARVER",
    drive: "AWD",
    mass: 193,
    power: 19,
    maxSpeed: 39,
    grip: 10.8,
    brake: 28,
    color: "#bed45a",
    body: 1,
    text: "Planted through every apex.",
  },
  {
    id: "comet",
    name: "Comet X",
    tag: "THE STRAIGHT-LINE SPECIALIST",
    drive: "RWD",
    mass: 154,
    power: 15.5,
    maxSpeed: 48,
    grip: 7.1,
    brake: 23,
    color: "#86bbd2",
    body: 2,
    text: "Built for the horizon.",
  },
];
export const DRIVERS = [
  {
    name: "Jules Vega",
    title: "THE COASTAL LOCAL",
    bio: "Knows every corner. Always takes the scenic line.",
    helmet: "#f26535",
    suit: "#f0ebe0",
    number: "07",
  },
  {
    name: "Remi Cross",
    title: "THE NIGHT SHIFT",
    bio: "Quiet on the radio. Loud on the timing sheets.",
    helmet: "#b9cf56",
    suit: "#243438",
    number: "24",
  },
  {
    name: "Sora Vale",
    title: "THE TRAILBLAZER",
    bio: "A rally heart with a circuit-racing obsession.",
    helmet: "#6da8c5",
    suit: "#e5cfb0",
    number: "81",
  },
];
export const COLORS = [
  "#f26535",
  "#bdd15c",
  "#83b9cc",
  "#eee9df",
  "#d44c54",
  "#343e49",
  "#dfb569",
  "#75866b",
];
export const ITEMS = {
  turbo: {
    name: "Surge",
    key: "SUR",
    description: "Three seconds of extra thrust.",
  },
  shield: {
    name: "Halo",
    key: "HAL",
    description: "Five seconds of impact protection.",
  },
  emp: {
    name: "Pulse",
    key: "EMP",
    description: "Slows nearby unshielded rivals.",
  },
};
export const DEFAULT_PROFILE = {
  version: 1,
  vehicle: "vortex",
  color: "#f26535",
  finish: "metallic",
  spoiler: true,
  driver: 0,
  helmet: "#f26535",
  suit: "#f0ebe0",
  number: "07",
  tuning: { engine: 1, grip: 1, aero: 0.5, steering: 1 },
  settings: {
    quality: "high",
    engine: 0.45,
    effects: 0.5,
    music: 0.18,
    camera: 0,
    sensitivity: 1,
    deadzone: 0.12,
    reducedMotion: false,
    assist: true,
    bindings: {
      throttle: "KeyW",
      brake: "KeyS",
      left: "KeyA",
      right: "KeyD",
      drift: "Space",
      boost: "ShiftLeft",
      item: "KeyE",
      reset: "KeyR",
      camera: "KeyC",
    },
  },
  records: {},
  presets: [],
  races: 0,
  wins: 0,
  distance: 0,
};
export function vehicleStats(profile) {
  const v = VEHICLES.find((v) => v.id === profile.vehicle) || VEHICLES[0];
  const t = profile.tuning;
  return {
    ...v,
    mass: v.mass + (t.engine - 1) * 20,
    power: v.power * t.engine,
    maxSpeed: v.maxSpeed + (t.engine - 1) * 5 - t.aero * 2.5,
    grip: v.grip * t.grip,
    drag: 0.006 + t.aero * 0.003,
    aero: t.aero,
    steering: t.steering,
    brake: v.brake * (0.9 + t.grip * 0.1),
  };
}
